---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without acceptance release
rvm:
  - 2.5.0
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
stages:
  - validate
  - spec
  - acceptance
  - build
matrix:
  fast_finish: true
  include:
    - stage: acceptance
      bundler_args: --without release
      env: CHECK=beaker
      services: docker
      sudo: required
    - stage: validate
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    - stage: spec
      env: CHECK=spec
    - stage: spec
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=spec
      rvm: 2.4.4
    - stage: spec
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=spec
      rvm: 2.1.9
    - stage: build
      bundler_args: --without acceptance
      env: CHECK=build DEPLOY_TO_FORGE=yes
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: edgej
  password:
    secure: "nwH+GMIILYvDvtMQfPISYR+Vzl4dBxz829oN8doqf+xdlskE81r79oW30Tt/tQdKd4gT8K06pPcxLaZu0R2KlMw0Uxx91mKXxY+LrH2squ92cKbHPKZrYiYNd24swlGgBq7+nTtc3/q7n+wYrMwpria/uC1q+SdRsQjJzNVQ74sZIUEEGbFOPL3AgKQKU8IQH+5NhvYCo9E/ISCmN7l419Xh7Z6/VEEEn3rj9q4LhdQIkkapDXnFKQI/0YUeQWZneSyRhWIJk5WmQQttYtFY5tm7t2ifS20Q3haOBnKhvkUlX8xZhQU8g1+UgmIcTAm9c0+NRFz7N/YAMWpLXgVMh5bBAR5CFrTUzWDKULG4GLV9uZienlENbAhJBF5vNcXJUK4fFrwmts8NOcFLITaHhieHjg7zw2Pyab38YPdqBg2lCSPPFkxb+/agsONPN4RQ116TtgO/BMx2GUnhssgYb1hRwtRuWMy2Ob270Y7MvkwU7r6Uw+wDAkz8tqiPmte10i+t91iGewnYyMxsbIIsyMx46w5IpFqpTvXxCwVPMX0Eet/pb4wkVah2nJiUalzdaLy/vvuLeIAl0Kz+5WrOeWaK0rkq1oFhxm17db+ZUX/F3hiXuXGkov1o/D2rtVv/a9TG+Um1UZMc1tqUvVXoYpCGaFv5yvgPysaSy1fdwXk="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
