---
HOSTS:
  ubuntu-1804-x64:
    platform: ubuntu-18.04-amd64
    hypervisor: docker
    image: ubuntu:18.04
    docker_preserve_image: true
  ubuntu-2004-x64:
    platform: ubuntu-20.04-amd64
    hypervisor: docker
    image: ubuntu:20.04
    docker_preserve_image: true
CONFIG:
  type: foss
  trace_limit: 200
